web:
  build: .
  environment:
    - AWS_ACCOUNTID=convox-dev
    - AWS_REGION
    - AWS_ACCESS
    - AWS_SECRET
    - CLUSTER
    - CUSTOM_TOPIC
    - DEVELOPMENT=true
    - HTTP_PASSWORD
    - MIXPANEL_TOKEN=43fb68427548c5e99978a598a9b14e55
    - REGISTRY_HOST
    - REGISTRY_PASSWORD
    - RELEASE=local
    - ROLLBAR_TOKEN=f67f25b8a9024d5690f997bd86bf14b0
    - SUBNETS
    - VPC
  ports:
    - 5000:3000
    - 4443:4443
  volumes:
    - ./:/go/src/github.com/convox/kernel
    - /var/run/docker.sock:/var/run/docker.sock
registry:
  environment:
    - REGISTRY_CERT_PUBLIC
    - REGISTRY_CERT_PRIVATE
    - SETTINGS_FLAVOR=local
  image: convox/registry
  ports:
    - 5100:443
